
package vista;

import brenda.listsingly.LinkedList;
import controlador.ControlEstacion;
import controlador.ControlLogin;
import controlador.ControlRutas;
import controlador.ControlTren;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Tren;

/**
 *
 * @author BRENDA
 */
public class ConsultarTren extends javax.swing.JFrame {
    
    LinkedList<Tren> trenes;

    DefaultTableModel mt = new DefaultTableModel();
    ControlTren tr;

    public ConsultarTren() {
        initComponents();
        tr = new ControlTren();
        mt = new DefaultTableModel();
        String[] ids = {"id", "nombre", "carga", "kilometraje"};
        mt.setColumnIdentifiers(ids);
        jTable1.setModel(mt);
        trenes = tr.consultarTrenDisponibles();
        cargarRutasEnTabla(trenes);
    }

    private void cargarRutasEnTabla(LinkedList<Tren> rutas) {
        for (int i = 0; i < rutas.size(); i++) {
            Object[] fila = {
                rutas.get(i).getIdentificador(),
                rutas.get(i).getNombre(),
                rutas.get(i).getCapacidadCarga(),
                rutas.get(i).getKilometraje()
            };
            mt.addRow(fila);
        }
    }

    private void cargarRutaEnTabla(Tren rutas) {
        Object[] fila = {
            rutas.getIdentificador(),
            rutas.getNombre(),
            rutas.getCapacidadCarga(),
            rutas.getKilometraje()
        };
        mt.addRow(fila);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        modificarFrame = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        borrarFrame = new javax.swing.JButton();
        crearFrame = new javax.swing.JButton();
        idFrame = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombreFrame = new javax.swing.JComboBox<>();
        salirFrame = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 153));
        jLabel8.setText("*+:｡.｡");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 153));
        jLabel9.setText("*+:｡.｡");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 183, 216));

        jPanel4.setBackground(new java.awt.Color(255, 234, 244));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));

        modificarFrame.setBackground(new java.awt.Color(255, 133, 214));
        modificarFrame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modificarFrame.setForeground(new java.awt.Color(153, 0, 102));
        modificarFrame.setText("Modificar");
        modificarFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        modificarFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarFrameMouseClicked(evt);
            }
        });
        modificarFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarFrameActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "nombre", "carga", "kilometraje"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        borrarFrame.setBackground(new java.awt.Color(255, 133, 214));
        borrarFrame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        borrarFrame.setForeground(new java.awt.Color(153, 0, 102));
        borrarFrame.setText("Dar Baja");
        borrarFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        borrarFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarFrameMouseClicked(evt);
            }
        });
        borrarFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarFrameActionPerformed(evt);
            }
        });

        crearFrame.setBackground(new java.awt.Color(255, 133, 214));
        crearFrame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        crearFrame.setForeground(new java.awt.Color(153, 0, 102));
        crearFrame.setText("Crear");
        crearFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        crearFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearFrameMouseClicked(evt);
            }
        });
        crearFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearFrameActionPerformed(evt);
            }
        });

        idFrame.setBackground(new java.awt.Color(255, 153, 204));
        idFrame.setForeground(new java.awt.Color(102, 0, 102));
        idFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        idFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFrameActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 153));
        jLabel12.setText("ID:");

        jLabel14.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 153));
        jLabel14.setText("Nombre:");

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 153));
        jLabel7.setText("Consultar Trenes");

        nombreFrame.setBackground(new java.awt.Color(255, 153, 204));
        nombreFrame.setForeground(new java.awt.Color(102, 0, 102));
        nombreFrame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arnold", "Mercedes-Benz" }));
        nombreFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        nombreFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFrameActionPerformed(evt);
            }
        });

        salirFrame.setBackground(new java.awt.Color(255, 133, 214));
        salirFrame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salirFrame.setForeground(new java.awt.Color(153, 0, 102));
        salirFrame.setText("Salir");
        salirFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        salirFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirFrameMouseClicked(evt);
            }
        });
        salirFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirFrameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(modificarFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idFrame)
                                .addComponent(nombreFrame, 0, 151, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(crearFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(borrarFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(salirFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(nombreFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salirFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reload(){
        ConsultarTren cr = new ConsultarTren();
        cr.setVisible(true);
        this.dispose();
    }

    private void modificarFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarFrameMouseClicked
        ControlMoTren mm = new ControlMoTren();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_modificarFrameMouseClicked

    private void modificarFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarFrameActionPerformed

    }//GEN-LAST:event_modificarFrameActionPerformed

    private void borrarFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarFrameMouseClicked
        String id = JOptionPane.showInputDialog("Cual desea dar de baja?");
        if (tr.bajarTren(id)) {
            reload();
        }else{
           JOptionPane.showMessageDialog(this, "Tren no disponible"); 
        }
    }//GEN-LAST:event_borrarFrameMouseClicked

    private void borrarFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarFrameActionPerformed

    private void crearFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearFrameMouseClicked
        String id = idFrame.getText();
        String nombre = (String) nombreFrame.getSelectedItem();
        tr.agregarTrenEnLista(tr.convertirObjecto(id, nombre));
        cargarRutaEnTabla(tr.convertirObjecto(id, nombre));
    }//GEN-LAST:event_crearFrameMouseClicked

    private void crearFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearFrameActionPerformed
       
    }//GEN-LAST:event_crearFrameActionPerformed

    private void idFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFrameActionPerformed

    private void nombreFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFrameActionPerformed

    private void salirFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirFrameMouseClicked
        ControlFrame cf = new ControlFrame();
        cf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirFrameMouseClicked

    private void salirFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarTren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarTren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarTren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarTren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarTren().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarFrame;
    private javax.swing.JButton crearFrame;
    private javax.swing.JTextField idFrame;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificarFrame;
    private javax.swing.JComboBox<String> nombreFrame;
    private javax.swing.JButton salirFrame;
    // End of variables declaration//GEN-END:variables
}
