/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import brenda.listsingly.LinkedList;
import controlador.ControlBoleto;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import modelo.Boleto;

/**
 *
 * @author BRENDA
 */
public class ConsultarBoleto extends javax.swing.JFrame {

    ControlBoleto cb;
    DefaultTableModel mt;
    LinkedList<Boleto> boleto;

    public ConsultarBoleto() {
        initComponents();
        mt = new DefaultTableModel();
        try {
            try {
                cb = new ControlBoleto();
                boleto = new LinkedList<>();
            } catch (RemoteException ex) {
                Logger.getLogger(ConsultarBoleto.class.getName()).log(Level.SEVERE, null, ex);
            }
            String[] ids = {"fecha", "nombre", "apellido", "telefono1", "telefono2", "inicio", "fin", "trayecto", "id", "categoria", "equipaje", "precio", "tren"};
            mt.setColumnIdentifiers(ids);
            jTable1.setModel(mt);
            boleto = cb.consultarBoletos();
            cargarBoletos(boleto);
        } catch (RemoteException ex) {
            Logger.getLogger(ConsultarBoleto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void cargarBoletos(LinkedList<Boleto> boletos){
        for(int i = 0; i < boleto.size(); i++){
            Object[] fila = {
                boleto.get(i).getFechaCompra(),
                boleto.get(i).getCliente().getName(),
                boleto.get(i).getCliente().getLastName(),
                boleto.get(i).getCliente().getPhoneNumbers().get(0),
                boleto.get(i).getCliente().getPhoneNumbers().get(1),
                boleto.get(i).getTrayectoria().getInicio(),
                boleto.get(i).getTrayectoria().getFin(),
                boleto.get(i).getTrayectoria().getTrayecto(),
                boleto.get(i).getCliente().getIdentification(),
                boleto.get(i).getCategoria(),
                boleto.get(i).getEquipaje().getCantidadEquipajes(),
                boleto.get(i).getPrecioTotal(),
                boleto.get(i).getTren().getIdentificador()
            };
            mt.addRow(fila);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salirFrame = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        salirFrame1 = new javax.swing.JButton();
        salirFrame2 = new javax.swing.JButton();

        salirFrame.setBackground(new java.awt.Color(255, 133, 214));
        salirFrame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salirFrame.setForeground(new java.awt.Color(153, 0, 102));
        salirFrame.setText("Salir");
        salirFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        salirFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirFrameMouseClicked(evt);
            }
        });
        salirFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirFrameActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 183, 216));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "fechaCompra", "idTren", "nombre", "apellido", "telefono1", "telefono2", "inicio", "destino", "trayecto", "identificacion", "categoria", "equipaje", "precioTotal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 153));
        jLabel7.setText("Consultar Boletos");

        salirFrame1.setBackground(new java.awt.Color(255, 133, 214));
        salirFrame1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salirFrame1.setForeground(new java.awt.Color(153, 0, 102));
        salirFrame1.setText("Salir");
        salirFrame1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        salirFrame1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirFrame1MouseClicked(evt);
            }
        });
        salirFrame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirFrame1ActionPerformed(evt);
            }
        });

        salirFrame2.setBackground(new java.awt.Color(255, 133, 214));
        salirFrame2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salirFrame2.setForeground(new java.awt.Color(153, 0, 102));
        salirFrame2.setText("Validar Boleto");
        salirFrame2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        salirFrame2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirFrame2MouseClicked(evt);
            }
        });
        salirFrame2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirFrame2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(salirFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salirFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salirFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salirFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirFrameMouseClicked
       
    }//GEN-LAST:event_salirFrameMouseClicked

    private void salirFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirFrameActionPerformed

    private void salirFrame1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirFrame1MouseClicked
        ControlFrame cf;
        try {
            cf = new ControlFrame();
            cf.setVisible(true);
            this.dispose();
        } catch (RemoteException ex) {
            Logger.getLogger(ConsultarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_salirFrame1MouseClicked

    private void salirFrame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirFrame1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirFrame1ActionPerformed

    private void salirFrame2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirFrame2MouseClicked
        ValidarBoleto vb = new ValidarBoleto();
        vb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirFrame2MouseClicked

    private void salirFrame2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirFrame2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirFrame2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarBoleto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton salirFrame;
    private javax.swing.JButton salirFrame1;
    private javax.swing.JButton salirFrame2;
    // End of variables declaration//GEN-END:variables
}
