/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controlador.ControlLogger;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author BRENDA
 */
public class ControlFrame extends javax.swing.JFrame {

    ControlLogger cl;
    ConsultarTren tr;
    ConsultarRuta gr;

    public ControlFrame() throws RemoteException {
        initComponents();
        cl = new ControlLogger();
        tr = new ConsultarTren();
        gr = new ConsultarRuta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gestionRutas = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        gestionTren = new javax.swing.JButton();
        gestionRutas2 = new javax.swing.JButton();
        gestionRutas3 = new javax.swing.JButton();
        gestionRutas4 = new javax.swing.JButton();
        gestionRutas5 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 183, 216));

        jPanel4.setBackground(new java.awt.Color(255, 234, 244));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 153));
        jLabel1.setText("¡BIENVENIDO!");

        jLabel2.setForeground(new java.awt.Color(255, 0, 153));
        jLabel2.setText("*+:｡.｡");

        jLabel3.setForeground(new java.awt.Color(255, 0, 153));
        jLabel3.setText("*+:｡.｡");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 102));
        jLabel4.setText("______________________________________________________________________________________________");

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 153));
        jLabel5.setText("¿Qué acción desea realizar?");

        gestionRutas.setBackground(new java.awt.Color(255, 133, 214));
        gestionRutas.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        gestionRutas.setForeground(new java.awt.Color(153, 0, 102));
        gestionRutas.setText("Gestión Rutas");
        gestionRutas.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        gestionRutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionRutasMouseClicked(evt);
            }
        });
        gestionRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionRutasActionPerformed(evt);
            }
        });

        cerrarSesion.setBackground(new java.awt.Color(255, 133, 214));
        cerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cerrarSesion.setForeground(new java.awt.Color(153, 0, 102));
        cerrarSesion.setText("~Cerrar Sesión~");
        cerrarSesion.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        cerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionMouseClicked(evt);
            }
        });
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        gestionTren.setBackground(new java.awt.Color(255, 133, 214));
        gestionTren.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        gestionTren.setForeground(new java.awt.Color(153, 0, 102));
        gestionTren.setText("Gestión Trenes");
        gestionTren.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        gestionTren.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionTrenMouseClicked(evt);
            }
        });
        gestionTren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionTrenActionPerformed(evt);
            }
        });

        gestionRutas2.setBackground(new java.awt.Color(255, 133, 214));
        gestionRutas2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        gestionRutas2.setForeground(new java.awt.Color(153, 0, 102));
        gestionRutas2.setText("Historial Gestión");
        gestionRutas2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        gestionRutas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionRutas2MouseClicked(evt);
            }
        });
        gestionRutas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionRutas2ActionPerformed(evt);
            }
        });

        gestionRutas3.setBackground(new java.awt.Color(255, 133, 214));
        gestionRutas3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        gestionRutas3.setForeground(new java.awt.Color(153, 0, 102));
        gestionRutas3.setText("Gestión Estaciones");
        gestionRutas3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        gestionRutas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionRutas3MouseClicked(evt);
            }
        });
        gestionRutas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionRutas3ActionPerformed(evt);
            }
        });

        gestionRutas4.setBackground(new java.awt.Color(255, 133, 214));
        gestionRutas4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        gestionRutas4.setForeground(new java.awt.Color(153, 0, 102));
        gestionRutas4.setText("Gestión Boleto");
        gestionRutas4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        gestionRutas4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionRutas4MouseClicked(evt);
            }
        });
        gestionRutas4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionRutas4ActionPerformed(evt);
            }
        });

        gestionRutas5.setBackground(new java.awt.Color(255, 133, 214));
        gestionRutas5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        gestionRutas5.setForeground(new java.awt.Color(153, 0, 102));
        gestionRutas5.setText("Gestión Empleados");
        gestionRutas5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        gestionRutas5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionRutas5MouseClicked(evt);
            }
        });
        gestionRutas5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionRutas5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(130, 130, 130))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(gestionRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gestionTren, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gestionRutas3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(gestionRutas2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(gestionRutas4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gestionRutas5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gestionRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gestionTren, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gestionRutas3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gestionRutas2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gestionRutas4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gestionRutas5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionRutasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionRutasMouseClicked

        cl.agregarEnLista("Se consultaron las rutas disponibles");
        gr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestionRutasMouseClicked

    private void gestionRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionRutasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionRutasActionPerformed

    private void cerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionMouseClicked
        LoginFrame lf = new LoginFrame();
        cl.agregarEnLista("Se ha cerrado sesion");
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarSesionMouseClicked

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed

    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void gestionTrenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionTrenMouseClicked

        cl.agregarEnLista("Se consultaron los trenes disponibles");
        tr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestionTrenMouseClicked

    private void gestionTrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionTrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionTrenActionPerformed

    private void gestionRutas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionRutas2MouseClicked
        ConsultarLogger ck = new ConsultarLogger();
        this.cl.agregarEnLista("Se consulto el historial de acciones");
        ck.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestionRutas2MouseClicked

    private void gestionRutas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionRutas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionRutas2ActionPerformed

    private void gestionRutas3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionRutas3MouseClicked
        try {
            ConsultarEstacion ce = new ConsultarEstacion();
            cl.agregarEnLista("Se consultaron las estaciones disponibles");
            ce.setVisible(true);
            this.dispose();
        } catch (RemoteException ex) {
            Logger.getLogger(ControlFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gestionRutas3MouseClicked

    private void gestionRutas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionRutas3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionRutas3ActionPerformed

    private void gestionRutas4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionRutas4MouseClicked
        ConsultarBoleto cbb = new ConsultarBoleto();
        cbb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestionRutas4MouseClicked

    private void gestionRutas4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionRutas4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionRutas4ActionPerformed

    private void gestionRutas5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionRutas5MouseClicked
        LoginFrameAdmin lf = new LoginFrameAdmin();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestionRutas5MouseClicked

    private void gestionRutas5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionRutas5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionRutas5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ControlFrame().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(ControlFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JButton gestionRutas;
    private javax.swing.JButton gestionRutas2;
    private javax.swing.JButton gestionRutas3;
    private javax.swing.JButton gestionRutas4;
    private javax.swing.JButton gestionRutas5;
    private javax.swing.JButton gestionTren;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
