/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import brenda.listsingly.LinkedList;
import controlador.ControlBoleto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import modelo.Boleto;

/**
 *
 * @author BRENDA
 */
public class ValidarBoleto extends javax.swing.JFrame {

    ControlBoleto cb;
    DefaultTableModel mt;

    public ValidarBoleto() {
        initComponents();
        try {
            mt = new DefaultTableModel();
            cb = new ControlBoleto();
        } catch (RemoteException ex) {
            Logger.getLogger(ValidarBoleto.class.getName()).log(Level.SEVERE, null, ex);
        }

        String[] ids = {"fecha", "nombre", "apellido", "telefono1", "telefono2", "inicio", "fin", "trayecto", "id", "categoria", "equipaje", "precio", "tren"};
        mt.setColumnIdentifiers(ids);
        jTable1.setModel(mt);

        nombreCliFrame.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrarTabla();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrarTabla();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrarTabla();
            }
        });
    }

    private void filtrarTabla() {
        String nombreInicial = nombreCliFrame.getText().toUpperCase();
        mt.setRowCount(0);

        if (nombreInicial.length() >= 4) {
            try {
                LinkedList<Boleto> boletosAux = cb.consultarPorInicial(nombreInicial);


                cargarBoletos(boletosAux);
                jTable1.repaint();
            } catch (RemoteException ex) {
                Logger.getLogger(ValidarBoleto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void cargarBoletos(LinkedList<Boleto> boletos) {
        for (int i = 0; i < boletos.size(); i++) {
            Object[] fila = {
                boletos.get(i).getFechaCompra(),
                boletos.get(i).getCliente().getName(),
                boletos.get(i).getCliente().getLastName(),
                boletos.get(i).getCliente().getPhoneNumbers().get(0),
                boletos.get(i).getCliente().getPhoneNumbers().get(1),
                boletos.get(i).getTrayectoria().getInicio(),
                boletos.get(i).getTrayectoria().getFin(),
                boletos.get(i).getTrayectoria().getTrayecto(),
                boletos.get(i).getCliente().getIdentification(),
                boletos.get(i).getCategoria(),
                boletos.get(i).getEquipaje().getCantidadEquipajes(),
                boletos.get(i).getPrecioTotal(),
                boletos.get(i).getTren().getIdentificador()
            };
            mt.addRow(fila);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        salirFrame = new javax.swing.JButton();
        valiBoleFrame = new javax.swing.JButton();
        nombreCliFrame = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 183, 216));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "fechaCompra", "idTren", "nombre", "apellido", "telefono1", "telefono2", "inicio", "destino", "trayecto", "identificacion", "categoria", "equipaje", "precioTotal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 153));
        jLabel7.setText("Validar Boleto");

        salirFrame.setBackground(new java.awt.Color(255, 133, 214));
        salirFrame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salirFrame.setForeground(new java.awt.Color(153, 0, 102));
        salirFrame.setText("Salir");
        salirFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        salirFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirFrameMouseClicked(evt);
            }
        });
        salirFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirFrameActionPerformed(evt);
            }
        });

        valiBoleFrame.setBackground(new java.awt.Color(255, 133, 214));
        valiBoleFrame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        valiBoleFrame.setForeground(new java.awt.Color(153, 0, 102));
        valiBoleFrame.setText("Validar Boleto");
        valiBoleFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        valiBoleFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                valiBoleFrameMouseClicked(evt);
            }
        });
        valiBoleFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valiBoleFrameActionPerformed(evt);
            }
        });

        nombreCliFrame.setBackground(new java.awt.Color(255, 153, 204));
        nombreCliFrame.setForeground(new java.awt.Color(102, 0, 102));
        nombreCliFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 153), new java.awt.Color(204, 0, 153)));
        nombreCliFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCliFrameActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 153));
        jLabel14.setText("Nombre del Cliente:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(salirFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valiBoleFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreCliFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(nombreCliFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salirFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valiBoleFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirFrameMouseClicked
        ConsultarBoleto cf;
        cf = new ConsultarBoleto();
        cf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirFrameMouseClicked

    private void salirFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirFrameActionPerformed

    private void valiBoleFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valiBoleFrameMouseClicked
        try {
            String id = JOptionPane.showInputDialog("Ingrese la identificación");
            if(cb.consultarPorId(id) == true){
                JOptionPane.showMessageDialog(null, "Boleto valido");
            }else{
                JOptionPane.showMessageDialog(null, "Boleto no es valido");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(ValidarBoleto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_valiBoleFrameMouseClicked

    private void valiBoleFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valiBoleFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valiBoleFrameActionPerformed

    private void nombreCliFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCliFrameActionPerformed
        
    }//GEN-LAST:event_nombreCliFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidarBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidarBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidarBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidarBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidarBoleto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombreCliFrame;
    private javax.swing.JButton salirFrame;
    private javax.swing.JButton valiBoleFrame;
    // End of variables declaration//GEN-END:variables
}
